### ISSUE TITLE
Yambo/QE   example workflows  fail.

### ISSUE THREAD

**Issue by mikeatm** [marvel-nccr/marvel-virtualmachine#26]
Could not get  Yambo/QE workflow to run, (from the examples on the release page) or one of my own.
here is a traceback:

```
[2017-11-03 19:23:59,875: WARNING/Worker-2] Failed to load checkpoint '/home/vagrant/.aiida/repository-aiida/workflows/running/434.pickle' (deleting)
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/aiida/local/lib/python2.7/site-packages/aiida/work/persistence.py", line 168, in load_all_processes
    process = self.create_from_file_and_persist(f)
  File "/home/vagrant/.virtualenvs/aiida/local/lib/python2.7/site-packages/aiida/work/persistence.py", line 201, in create_from_file_and_persist
    process = Process.create_from(checkpoint)
  File "/home/vagrant/.virtualenvs/aiida/local/lib/python2.7/site-packages/plum/process.py", line 123, in create_from
    proc.perform_create(saved_instance_state=saved_instance_state)
  File "/home/vagrant/.virtualenvs/aiida/local/lib/python2.7/site-packages/plum/process.py", line 360, in perform_create
    self.on_create(pid, inputs, saved_instance_state)
  File "/home/vagrant/.virtualenvs/aiida/local/lib/python2.7/site-packages/aiida/work/workchain.py", line 297, in on_create
    self._aborted = saved_state[self._ABORTED]
  File "/home/vagrant/.virtualenvs/aiida/local/lib/python2.7/site-packages/aiida/work/workchain.py", line 229, in _aborted
    self.calc._set_attr(self.calc.ABORTED_KEY, True)
  File "/home/vagrant/.virtualenvs/aiida/local/lib/python2.7/site-packages/aiida/orm/mixins.py", line 68, in _set_attr
    "Cannot change the attributes of a sealed calculation.")
ModificationNotAllowed: Cannot change the attributes of a sealed calculation.

```

Minimum working  WF to reproduce:
```

from aiida.backends.utils import load_dbenv, is_dbenv_loaded
if not is_dbenv_loaded():
    load_dbenv()

from aiida_yambo.workflows.yambowf  import YamboWorkflow
from aiida_yambo.workflows.pwplaceholder  import PwRestartWf
from aiida_yambo.workflows.yambo_utils import default_step_size, update_parameter_field, set_default_qp_param,\
               default_pw_settings, set_default_pw_param, yambo_default_settings, default_qpkrange, p2y_default_settings
from aiida_quantumespresso.workflows.pw.base import PwBaseWorkChain

from aiida.orm.data.base import Float, Str, NumericType, BaseType, Bool, List  
from aiida.work.run import run, submit

from aiida.orm.utils import DataFactory
ParameterData = DataFactory("parameter")
StructureData = DataFactory('structure')

cell = [[4.2262023163, 0.0000000000, 0.0000000000],
        [0.0000000000, 4.2262023163, 0.0000000000],
        [0.0000000000, 0.0000000000, 2.7009939524],
       ]
struc = StructureData(cell=cell)
struc.append_atom(position=(1.2610450495  ,1.2610450495  ,0.0000000000  ), symbols='O')
struc.append_atom(position=(0.8520622471  ,3.3741400691  ,1.3504969762  ), symbols='O')
struc.append_atom(position=(2.9651572668  ,2.9651572668  ,0.0000000000  ), symbols='O')
struc.append_atom(position=(3.3741400691  ,0.8520622471  ,1.3504969762  ), symbols='O')
struc.append_atom(position=( 0.0000000000 , 0.0000000000 , 0.0000000000 ), symbols='Ti')
struc.append_atom(position=( 2.1131011581 , 2.1131011581 , 1.3504969762 ), symbols='Ti')

struc.store()

pw_parameters =  {
          'CONTROL': {
              'calculation': 'scf',
              'restart_mode': 'from_scratch',
              'wf_collect': True,
              'tprnfor': True,
              'etot_conv_thr': 0.00001,
              'forc_conv_thr': 0.0001,
              'verbosity' :'high',
              },
          'SYSTEM': {
              'ecutwfc': 35.,
              },
          'ELECTRONS': {
              'conv_thr': 1.e-8,
              'electron_maxstep ': 100,
              'mixing_mode': 'plain',
              'mixing_beta' : 0.3,
              } } 

calculation_set_pw ={'resources':  {"num_machines": 1,"num_mpiprocs_per_machine": 2}, 'max_wallclock_seconds': 8*60*60,
                  'environment_variables': {"OMP_NUM_THREADS": "0" }  }

settings_pw =  ParameterData(dict= {})

KpointsData = DataFactory('array.kpoints')
kpoints = KpointsData()
kpoints.set_kpoints_mesh([2,2,2])

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description='GW QP calculation.')
    parser.add_argument('--pseudo', type=str, dest='pseudo', required=True,
                        help='The pesudo  to use')
    parser.add_argument('--pwcode', type=str, dest='pwcode', required=True,
                        help='The QE code  to use')
    parser.add_argument('--structure', type=int, dest='structure', required=False,
                        help='The structure  to use')

    args = parser.parse_args()

    inputs = {}
    inputs['structure'] = struc
    inputs['code'] = Code.get_from_string( args.pwcode)
    inputs['options'] = ParameterData(dict=calculation_set_pw)
    inputs['kpoints']=kpoints
    inputs['parameters'] = ParameterData(dict=pw_parameters)
    inputs['pseudo_family'] =  Str(args.pseudo)
    inputs['settings']  = settings_pw  
    future = submit( PwBaseWorkChain, **inputs)
    print("run {}".format(future))
```

**Comment by ltalirz** [comment]
I'll have a look into that.
We now fixed a problem with PBS which caused the jobs to remain queued and on the fixed machine (which I'll try to make available this evening), I can run `verdi run test_mike.py  --pseudo sssp-pbe-accuracy --pwcode qe-pw-6.1@localhost`
It doesn't seem to produce anything, though?

**Comment by mikeatm** [comment]
look at the  daemon log when you run,  the workflow  dies immediately,   t observe you can change the submit to a run and keep it in the foreground.

**Comment by AntimoMarrazzo** [comment]
What's the status now? is it solved?

**Comment by ltalirz** [comment]
Hi Antimo,

I haven't tried it again. All I can say that the siesta workflow runs without problems.
If you think it is an issue specific to the machine, please let me know and I will investigate.

**Comment by mikeatm** [comment]
@AntimoMarrazzo   the underlying issue is now solved in RC2.

**Comment by ltalirz** [comment]
@mikeatm Thanks for trying it out, I'll close this for now (work on other open issues continues).
